---
- name: Install Docker Compose on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Ensure curl is installed
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Download Docker Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: "/usr/local/bin/docker-compose"
        mode: 'u+x'
      vars:
        docker_compose_version: "1.29.2"  # Update to your desired version

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version_output
      changed_when: false

    